// Builds src/corpus.generated.ts from the portfolio site's content files.
// The site and the chatbot share one content source: update a markdown file,
// re-run `npm run build:corpus`, redeploy the Worker.
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = join(here, '..', '..');
const out = join(here, '..', 'src', 'corpus.generated.ts');

async function readDirMarkdown(dir) {
  const entries = await readdir(dir, { withFileTypes: true, recursive: true });
  const files = entries
    .filter((e) => e.isFile() && e.name.endsWith('.md'))
    .map((e) => join(e.parentPath ?? e.path, e.name))
    .sort();
  return Promise.all(files.map((f) => readFile(f, 'utf8')));
}

function isDraft(markdown) {
  const fm = markdown.match(/^---\n([\s\S]*?)\n---/);
  return fm ? /^draft:\s*true\s*$/m.test(fm[1]) : false;
}

const site = JSON.parse(await readFile(join(siteRoot, 'src/data/site.json'), 'utf8'));
const experience = await readDirMarkdown(join(siteRoot, 'src/content/experience'));
const projects = await readDirMarkdown(join(siteRoot, 'src/content/projects'));
const blog = (await readDirMarkdown(join(siteRoot, 'src/content/blog'))).filter(
  (md) => !isDraft(md)
);

const sections = [
  `# Profile\n\n${JSON.stringify(site, null, 2)}`,
  `# Work Experience\n\n${experience.join('\n\n---\n\n')}`,
  `# Projects\n\n${projects.join('\n\n---\n\n')}`,
  `# Blog Posts\n\n${blog.join('\n\n---\n\n')}`,
];

const corpus = sections.join('\n\n\n');
const escaped = corpus.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

await writeFile(
  out,
  `// GENERATED by scripts/build-corpus.mjs — do not edit by hand.\n// Re-run \`npm run build:corpus\` after changing site content.\nexport const CORPUS = \`${escaped}\`;\n`
);

console.log(`Wrote ${out} (${corpus.length} chars, ~${Math.round(corpus.length / 4)} tokens)`);
