// GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Re-run `npm run build:corpus` after changing site content.
export const CORPUS = `# Profile

{
  "name": "Rajat Manish Bhagat",
  "brandName": "Rajat Bhagat",
  "heroGreeting": "Hi, I'm Rajat 👋",
  "tagline": "Software engineer specializing in data platforms, cloud infrastructure, and backend systems. Most recently an Associate Principal Software Engineer on the Data Platform team at The Options Clearing Corporation.",
  "openToCallout": "🔍 Open to new opportunities in the Data Platform space",
  "location": "Chicago, USA",
  "email": "rajat.bhagat@gmail.com",
  "linkedin": "https://www.linkedin.com/in/rmbhagat/",
  "github": "https://github.com/rajatbhagat",
  "resume": "/Rajat-Bhagat-Resume.pdf",
  "metaDescription": "Rajat Manish Bhagat — Software Engineer specializing in data platforms, cloud, and backend systems.",
  "skills": [
    {
      "group": "Languages",
      "items": "Java, Python, TypeScript, JavaScript, Terraform, Ansible, C"
    },
    {
      "group": "Web & Frameworks",
      "items": "Spring Boot, Node.js, React, Redux, Next.js, Django, JUnit"
    },
    {
      "group": "Databases",
      "items": "Snowflake, PostgreSQL, Oracle Database, MySQL, MongoDB"
    },
    {
      "group": "Cloud & Tools",
      "items": "AWS, Kafka, OpenShift, Oracle Cloud, Kubernetes, Docker, Jenkins, Git, Linux"
    }
  ],
  "highlights": [
    "7+ years of software engineering experience across fintech and cloud",
    "Master's in Computer Science, Northeastern University (GPA: 4.0)",
    "AWS Certified Solutions Architect – Associate (2025)",
    "Oracle Cloud Infrastructure Associate Architect & Cloud Developer Professional (2023)",
    "Impact Award recipient, 2 consecutive years at JP Morgan Chase"
  ],
  "education": {
    "school": "Northeastern University, Boston",
    "degree": "Master's in Computer Science",
    "period": "Aug 2021 – May 2023",
    "detail": "GPA: 4.0"
  },
  "certifications": [
    "AWS Certified Solutions Architect – Associate (2025)",
    "Oracle Cloud Infrastructure Associate Architect (2023)",
    "Oracle Cloud Infrastructure Cloud Developer Professional (2023)",
    "Impact Award for 2 consecutive years at JP Morgan Chase"
  ]
}


# Work Experience

---
company: Discover Financial Services
location: Chicago, US
title: Application Engineer
period: Apr 2024 – Oct 2025
order: 2
---

- Developed and enhanced the team's Python configuration-deployment microservice orchestrating generation and deployment of 200,000+ artifacts; designed and implemented its TOML-based deployment and grouped-DDL deployment features
- Enhanced a custom reconciliation framework with reusable validation controls for custom reconciliation balances, improving data-quality assurance across 400 data pipelines
- Led feature testing and post-production support for a monitoring-and-controls capability, coordinating with 5 cross-functional teams
- Served as the subject-matter expert for the legacy enterprise data platform (1M+ records processed daily) through the post-acquisition data migration, leading working sessions with Capital One to identify unused legacy datasets and their owners
- Mitigated the late-2025 AWS outage for the legacy platform, replaying 5,000+ data pipelines and 40,000+ files to ensure zero data loss
- Led setup of Kafka streaming ingestion for the next-generation data ecosystem; drove the team's Datadog migration and vulnerability remediation; mentored a summer intern and served on the production-support roster


---

---
company: JP Morgan Chase
location: Mumbai, India
title: Software Engineer II
period: Jul 2018 – Jul 2021
order: 4
---

- Core member of the team that built a trade-document digitization platform from the ground up — five Java/Python microservices communicating over Kafka (OCR, NLP, ML data extraction, audit trail, and a React/Redux application layer) — replacing manual compliance review and processing 700+ transactions daily
- Built the Python OCR service with a multi-engine voting algorithm, extended it to multilingual OCR (Mandarin, Hindi), and migrated it to AWS EC2 with autoscaling groups and Ansible-automated provisioning
- Developed the NLP service (Java Spring Boot, Apache OpenNLP plus custom-trained models) extracting entities, SWIFT and container codes, currencies, and amounts at 96% average accuracy
- Led a team of 3 building document data extraction: per-document-type spaCy models trained on 3,000+ documents, plus a template-based extractor reaching 99% accuracy on standardized documents — work recognized with Impact Awards in 2018 and 2019
- Built a trade-inquiry chatbot on Symphony (Java Spring Boot, AIML query mapping) that let operations teams self-serve transaction-document lookups, cutting manual inquiries by 40%
- Automated straight-through processing of claim transactions on the bank's legacy trade platform using MuleSoft integrations and a spaCy model to flag high-value cases for review, automating 60% of transactions
- Coordinated 20 production releases over two years, handling change management across multiple teams and clients


---

---
company: Mythics LLC
location: Arlington, US
title: Cloud Developer
period: Jun 2023 – Mar 2024
order: 3
---

- Built FinOps automation ingesting OCI Cost & Usage reports for 24 tenancies (50,000+ records daily) into Oracle Database, reading tenancy credentials from OCI Vault under instance-scoped access policies so private keys were never stored locally
- Developed the cost-monitoring portal (Next.js + TypeScript frontend, Node.js backend with TypeORM) generating reports over tables of 20M+ records; integrated Redis caching to cut report load times from ~1 minute to ~2 seconds; shipped as Docker images on Kubernetes
- Delivered patching-as-a-service for Oracle Exadata systems: Ansible playbooks for asynchronous patch download, pre-checks, patching, and post-patch validation, orchestrated by a Jenkins pipeline driven from JIRA ticket transitions — cutting patching time by 60% and enabling parallel patching with minimal engineer monitoring
- Shipped a weekly CIS-compliance security scan for OCI tenancies as a containerized OCI Function using policy-based auth (no stored credentials), reusable across any tenancy
- Built a portal for dynamic surveys and workflows on the same Next.js/Node.js stack, and provisioned OCI infrastructure for multiple customers using Terraform and Ansible


---

---
company: The Options Clearing Corporation
location: Chicago, US
title: Associate Principal Software Engineer — Data Platform
period: Nov 2025 – Jun 2026
order: 1
# TODO(Rajat): The bullets below are drafts — replace them with your actual work at OCC.
---

- Worked on the Data Platform team building and maintaining data infrastructure for clearing and risk operations
- Designed and developed data pipelines and platform services supporting business-critical workloads
- Collaborated with cross-functional teams to deliver reliable, well-governed data products



# Projects

---
name: Food Recommender
tech: [Node.js, JavaScript, MongoDB]
links:
  - label: GitHub
    url: https://github.com/rajatbhagat/food-recommender-server
order: 3
---

Backend server for a food recommendation application that suggests dishes and restaurants based on user preferences.


---

---
name: Hotel Reservation System
tech: [Java, Spring Boot, React, MySQL]
links:
  - label: Backend
    url: https://github.com/rajatbhagat/hotel-reservation-spring-boot
  - label: Frontend
    url: https://github.com/rajatbhagat/hotel-reservation-react-app
order: 2
---

A full-stack hotel booking application with a Spring Boot REST backend and a React frontend covering room search, reservations, and booking management.


---

---
name: Mini-S3
tech: [Java, Spring Boot, PostgreSQL, React, Next.js, TypeScript]
links:
  - label: Backend
    url: https://github.com/rajatbhagat/mini-s3
  - label: UI
    url: https://github.com/rajatbhagat/mini-s3-ui
order: 1
---

An S3-compatible object storage service built from scratch to understand object storage internals — bucket management, object versioning, custom metadata, and a RESTful API, plus a React/Next.js UI with drag-and-drop uploads.


---

---
name: Music Recommendation System
tech: [Python, Jupyter, scikit-learn]
links:
  - label: GitHub
    url: https://github.com/rajatbhagat/music-recommendation-system
order: 4
---

A machine-learning based music recommendation system exploring collaborative filtering and content-based approaches.



# Blog Posts

---
title: 'Building Mini-S3: Learning Object Storage by Reimplementing It'
description: 'Why I built an S3-compatible object storage service from scratch with Spring Boot and PostgreSQL, and what it taught me.'
pubDate: 2026-07-09
category: tech
tags: [java, spring-boot, aws, s3, postgresql]
---

I've used AWS S3 for years — uploading artifacts, hosting static assets, wiring it into data pipelines. But using a service and understanding it are different things. So I decided to build my own: [Mini-S3](https://github.com/rajatbhagat/mini-s3), an S3-compatible object storage service in Spring Boot and PostgreSQL, with a [React/Next.js UI](https://github.com/rajatbhagat/mini-s3-ui) on top.

## What it does

Mini-S3 implements the core ideas of object storage:

- **Buckets** — top-level containers with validation rules (naming, empty-bucket deletion checks)
- **Objects** — upload, download, and delete files with their metadata
- **Versioning** — every change to an object keeps its full history
- **Custom metadata** — arbitrary key-value pairs attached to objects at upload time
- **A RESTful API** — clean endpoints that mirror how S3's own API is shaped

The UI adds drag-and-drop uploads, bucket browsing, and metadata views in friendly tables.

## What building it taught me

**Versioning is a data-modeling problem, not a storage problem.** The interesting part isn't storing multiple copies — it's deciding what "the current version" means, how deletes interact with history, and how to keep queries fast when every object is really a chain of versions.

**Metadata design matters more than it looks.** S3's split between system metadata and user metadata seemed arbitrary until I had to implement both and realized they have completely different consistency and validation needs.

**API ergonomics come from constraints.** Reproducing S3-style semantics (like refusing to delete a non-empty bucket) forced me to think about *why* AWS made those choices — usually the answer is protecting users from themselves.

## Managing it like a real project

I ran the build like a work project, with a JIRA board, epics, and 175+ tasks. That sounds like overkill for a personal repo, but it kept the scope honest and made it easy to pick the project back up after breaks.

If you've ever wanted to demystify a cloud service you use daily, I highly recommend reimplementing a toy version. You'll never look at the real thing the same way.


---

---
title: 'Hello World: How This Blog Works'
description: 'The first post — and a living guide to how I add new posts and categories to this site.'
pubDate: 2026-07-09
category: tech
tags: [astro, meta, blogging]
---

Welcome! This is my corner of the internet — part portfolio, part blog. I'll write here about technology I'm working with, movies I've watched, and whatever else earns a category.

This first post doubles as documentation for future me: here's how the blog actually works.

## The stack

The site is built with [Astro](https://astro.build), a static site generator that treats markdown as a first-class citizen. Every page is pre-rendered to plain HTML, so it's fast and hosts for free on GitHub Pages. A GitHub Actions workflow rebuilds and deploys the site on every push to \`main\`.

## Adding a post

Each post is a single markdown file in \`src/content/blog/\`. To publish a new one, I add a file like this:

\`\`\`markdown
---
title: 'My New Post'
description: 'One-line summary shown in listings and search results.'
pubDate: 2026-08-01
category: tech
tags: [optional, tags]
---

The post content, in plain markdown.
\`\`\`

Commit, push, and it's live a minute later. That's the whole workflow.

## Categories are free

There's no registry of categories. The \`category\` frontmatter field can be anything — \`tech\`, \`movies\`, \`books\`, \`travel\` — and the site automatically generates a listing page at \`/blog/category/<name>/\` for every category that has at least one post. Adding a new category is just using it.

## Drafts

Setting \`draft: true\` in the frontmatter keeps a post out of the build entirely. I keep half-written posts in the repo without publishing them.

That's it — see you in the next post.
`;
