// GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Re-run `npm run build:corpus` after changing site content.
export const CORPUS = `# Profile

{
  "name": "Rajat Manish Bhagat",
  "brandName": "Rajat Bhagat",
  "heroGreeting": "Hi, I'm Rajat 👋",
  "tagline": "Software engineer specializing in data platforms, cloud infrastructure, and backend systems. Most recently an Associate Principal Software Engineer on the Data Platform team at The Options Clearing Corporation.",
  "openToCallout": "🔍 Open to new opportunities in the Data Platform space",
  "location": "Chicago, USA",
  "email": "rajat.bhagat@gmail.com",
  "linkedin": "https://www.linkedin.com/in/rmbhagat/",
  "github": "https://github.com/rajatbhagat",
  "resume": "https://rajatbhagat.github.io/Rajat-Bhagat-Resume.pdf",
  "metaDescription": "Rajat Manish Bhagat — Software Engineer specializing in data platforms, cloud, and backend systems.",
  "skills": [
    {
      "group": "Languages",
      "items": "Java, Python, TypeScript, JavaScript, Terraform, Ansible, C"
    },
    {
      "group": "Web & Frameworks",
      "items": "Spring Boot, Node.js, React, Redux, Next.js, Django, JUnit"
    },
    {
      "group": "Databases",
      "items": "Snowflake, PostgreSQL, Oracle Database, MySQL, MongoDB"
    },
    {
      "group": "Cloud & Tools",
      "items": "AWS, Kafka, OpenShift, Oracle Cloud, Kubernetes, Docker, Jenkins, Git, Linux"
    }
  ],
  "highlights": [
    "7+ years of software engineering experience across fintech and cloud",
    "Master's in Computer Science, Northeastern University (GPA: 4.0)",
    "AWS Certified Solutions Architect – Associate (2025)",
    "Oracle Cloud Infrastructure Associate Architect & Cloud Developer Professional (2023)",
    "Impact Award recipient, 2 consecutive years at JP Morgan Chase"
  ],
  "education": {
    "school": "Northeastern University, Boston",
    "degree": "Master's in Computer Science",
    "period": "Aug 2021 – May 2023",
    "detail": "GPA: 4.0"
  },
  "certifications": [
    "AWS Certified Solutions Architect – Associate (2025)",
    "Oracle Cloud Infrastructure Associate Architect (2023)",
    "Oracle Cloud Infrastructure Cloud Developer Professional (2023)",
    "Impact Award for 2 consecutive years at JP Morgan Chase"
  ],
  "chatEndpoint": "https://ask-my-resume.rajat-bhagat.workers.dev/chat",
  "siteUrl": "https://rajatbhagat.github.io"
}


# Work Experience

---
company: Discover Financial Services
location: Chicago, US
title: Application Engineer
period: Apr 2024 – Oct 2025
order: 2
---

- Developed and enhanced the team's Python configuration-deployment microservice orchestrating generation and deployment of 200,000+ artifacts; designed and implemented its TOML-based deployment and grouped-DDL deployment features
- Enhanced a custom reconciliation framework with reusable validation controls for custom reconciliation balances, improving data-quality assurance across 400 data pipelines
- Led feature testing and post-production support for a monitoring-and-controls capability, coordinating with 5 cross-functional teams
- Served as the subject-matter expert for the legacy enterprise data platform (1M+ records processed daily) through the post-acquisition data migration, leading working sessions with Capital One to identify unused legacy datasets and their owners
- Mitigated the late-2025 AWS outage for the legacy platform, replaying 5,000+ data pipelines and 40,000+ files to ensure zero data loss
- Led setup of Kafka streaming ingestion for the next-generation data ecosystem; drove the team's Datadog migration and vulnerability remediation; mentored a summer intern and served on the production-support roster


---

---
company: JP Morgan Chase
location: Mumbai, India
title: Software Engineer II
period: Jul 2018 – Jul 2021
order: 4
---

- Core member of the team that built a trade-document digitization platform from the ground up — five Java/Python microservices communicating over Kafka (OCR, NLP, ML data extraction, audit trail, and a React/Redux application layer) — replacing manual compliance review and processing 700+ transactions daily
- Built the Python OCR service with a multi-engine voting algorithm, extended it to multilingual OCR (Mandarin, Hindi), and migrated it to AWS EC2 with autoscaling groups and Ansible-automated provisioning
- Developed the NLP service (Java Spring Boot, Apache OpenNLP plus custom-trained models) extracting entities, SWIFT and container codes, currencies, and amounts at 96% average accuracy
- Led a team of 3 building document data extraction: per-document-type spaCy models trained on 3,000+ documents, plus a template-based extractor reaching 99% accuracy on standardized documents — work recognized with Impact Awards in 2018 and 2019
- Built a trade-inquiry chatbot on Symphony (Java Spring Boot, AIML query mapping) that let operations teams self-serve transaction-document lookups, cutting manual inquiries by 40%
- Automated straight-through processing of claim transactions on the bank's legacy trade platform using MuleSoft integrations and a spaCy model to flag high-value cases for review, automating 60% of transactions
- Coordinated 20 production releases over two years, handling change management across multiple teams and clients


---

---
company: Mythics LLC
location: Arlington, US
title: Cloud Developer
period: Jun 2023 – Mar 2024
order: 3
---

- Built FinOps automation ingesting OCI Cost & Usage reports for 24 tenancies (50,000+ records daily) into Oracle Database, reading tenancy credentials from OCI Vault under instance-scoped access policies so private keys were never stored locally
- Developed the cost-monitoring portal (Next.js + TypeScript frontend, Node.js backend with TypeORM) generating reports over tables of 20M+ records; integrated Redis caching to cut report load times from ~1 minute to ~2 seconds; shipped as Docker images on Kubernetes
- Delivered patching-as-a-service for Oracle Exadata systems: Ansible playbooks for asynchronous patch download, pre-checks, patching, and post-patch validation, orchestrated by a Jenkins pipeline driven from JIRA ticket transitions — cutting patching time by 60% and enabling parallel patching with minimal engineer monitoring
- Shipped a weekly CIS-compliance security scan for OCI tenancies as a containerized OCI Function using policy-based auth (no stored credentials), reusable across any tenancy
- Built a portal for dynamic surveys and workflows on the same Next.js/Node.js stack, and provisioned OCI infrastructure for multiple customers using Terraform and Ansible


---

---
company: The Options Clearing Corporation
location: Chicago, US
title: Associate Principal Software Engineer — Data Platform
period: Nov 2025 – Jun 2026
order: 1
# TODO(Rajat): The bullets below are drafts — replace them with your actual work at OCC.
---

- Worked on the Data Platform team building and maintaining data infrastructure for clearing and risk operations
- Designed and developed data pipelines and platform services supporting business-critical workloads
- Collaborated with cross-functional teams to deliver reliable, well-governed data products



# Projects

---
name: Ask My Resume
tech: [Cloudflare Workers, TypeScript, OpenRouter, LLMs, Astro, Workers KV]
links:
  - label: Try it live
    url: https://rajatbhagat.github.io/ask-my-resume/
  - label: Code
    url: https://github.com/rajatbhagat/rajatbhagat.github.io/tree/main/chatbot
  - label: Design doc
    url: https://rajatbhagat.github.io/blog/ask-my-resume-design/
date: 2026-07-15
---

An AI assistant embedded in this site that answers recruiter questions about my experience, grounded in the site's own content. A Cloudflare Worker proxies requests to an LLM (via OpenRouter) so the API key never reaches the browser — with streamed responses, a model picker, conversation memory, per-IP rate limiting, and prompt-injection defenses. Runs entirely on free tiers with no backend server to operate.


---

---
name: Food Recommender
tech: [Node.js, JavaScript, MongoDB]
links:
  - label: GitHub
    url: https://github.com/rajatbhagat/food-recommender-server
date: 2022-12-01
---

Backend server for a food recommendation application that suggests dishes and restaurants based on user preferences.


---

---
name: Hotel Reservation System
tech: [Java, Spring Boot, React, MySQL]
links:
  - label: Backend
    url: https://github.com/rajatbhagat/hotel-reservation-spring-boot
  - label: Frontend
    url: https://github.com/rajatbhagat/hotel-reservation-react-app
date: 2023-04-01
---

A full-stack hotel booking application with a Spring Boot REST backend and a React frontend covering room search, reservations, and booking management.


---

---
name: Mini-S3
tech: [Java, Spring Boot, PostgreSQL, React, Next.js, TypeScript]
links:
  - label: Backend
    url: https://github.com/rajatbhagat/mini-s3
  - label: UI
    url: https://github.com/rajatbhagat/mini-s3-ui
date: 2026-07-09
---

An S3-compatible object storage service built from scratch to understand object storage internals — bucket management, object versioning, custom metadata, and a RESTful API, plus a React/Next.js UI with drag-and-drop uploads.


---

---
name: Music Recommendation System
tech: [Python, Jupyter, scikit-learn]
links:
  - label: GitHub
    url: https://github.com/rajatbhagat/music-recommendation-system
date: 2022-09-01
---

A machine-learning based music recommendation system exploring collaborative filtering and content-based approaches.


---

---
name: Portfolio Website
tech: [Astro, TypeScript, GitHub Actions, GitHub Pages, Markdown]
links:
  - label: Live site
    url: https://rajatbhagat.github.io
  - label: Code
    url: https://github.com/rajatbhagat/rajatbhagat.github.io
date: 2026-07-10
---

This site — a statically generated portfolio and blog built with Astro. All content (experience, projects, blog posts) lives in Markdown through type-safe content collections, so adding a post or a role is a single file. Ships with light/dark theming, view transitions, RSS, and sitemap generation, and deploys automatically to GitHub Pages via a GitHub Actions pipeline.



# Blog Posts

---
title: 'Designing "Ask My Resume": A Serverless RAG-ready Chatbot on a Static Site'
description: 'A design walkthrough of the AI assistant on this site — how a GitHub Pages static site talks to an LLM safely, cheaply, and without a backend server.'
pubDate: 2026-07-16
category: tech
tags: [ai, llm, cloudflare-workers, astro, architecture, design-doc, open-router, claude-code]
draft: false
---

## TL;DR

[Ask My Resume](https://rajatbhagat.github.io/ask-my-resume/) is an LLM-based serverless chatbot designed to answer questions about my resume — education, work, projects and skills. The design relies on a serverless Worker provided by Cloudflare, which sends the user's request to OpenRouter to get a response from one of the chosen models. The bot also maintains some limited conversation context so the conversation can flow better rather than being a strict question-and-answer format. The setup and chosen technologies ensure that running the bot costs nothing, and it has guardrails to mitigate exploitative usage.

## Architecture overview

The architecture is pretty simple. A standard user request follows this flow:

- User asks a question on the UI (floating widget / ask-my-resume page)
- The request, along with the user's recent conversation history, is sent to the Cloudflare Worker
- The Worker validates the message and checks it against the rate limits, then forwards the request to OpenRouter
- OpenRouter runs the LLM and streams a response back, which is shown to the user

![Flow Diagram](images/ask-my-resume-flow.png)

## Components

### Frontend and UI (Astro island)

The UI is built with Astro and written in TypeScript. I owned the user-experience decisions — the floating widget and the dedicated \`/ask-my-resume\` page sharing a single component, incremental streaming of answers as they arrive, the model picker, and the mobile layout — and paired with Claude Code to implement and iterate on them.

### Cloudflare Worker

github.io websites are meant to be simple static pages, and the repository holding this website's code has to be a public repository accessible by everyone. That means it can't hold any sort of secret, including the OpenRouter API key. This was the main reason for creating a Cloudflare Worker: it can hold the API key safely and talk to the OpenRouter API to invoke the LLMs.

### LLM via OpenRouter

OpenRouter provides a whole host of models to choose from. I chose the three below, which seem to provide reliable and accurate output with a large token and parameter capacity:

- nvidia/nemotron-3-ultra-550b-a55b:free
- openai/gpt-oss-20b:free
- google/gemma-4-26b-a4b-it:free

The main drawback of using free models is the account-wide 50 requests/day limit. To keep any one visitor from exhausting that, a single user starts getting \`Rate Limit Exceeded\` messages after 16 questions in a day. Realistically a recruiter wouldn't go that far, so this rarely comes up. Adding OpenRouter credits or switching to a low-cost paid model would lift the daily cap.

### Corpus and System Prompt

The initial prototype only used my resume as the basis. Later I expanded on every job role and my duties within it, and stored a summary of that in the corpus. The entire corpus is approximately 3,000 tokens — small enough that context size isn't a concern. The initial idea was to build a RAG-based implementation to avoid consuming a lot of input tokens from the get-go. The current implementation includes the whole corpus in the system prompt, and the prompt also adds guardrails: it instructs the model to answer only from the corpus and to politely decline off-topic questions. The next step would be a RAG-based solution — but since the corpus is so small, RAG is unlikely to make a significant difference, so it stays a learning exercise for later rather than a necessity.

### Conversation memory

Maintaining conversation history was a significant problem to overcome. Without it, the bot would be less conversational and more of a question-and-answer page. History is kept by storing the previous questions and the bot's answers in the browser and sending them along with each new request. The Cloudflare Worker only uses the last 5 messages when building the prompt for the LLM — again, a measure to avoid filling up the token budget. Because the history lives in each visitor's browser, concurrent users never share context, and no conversation data is stored on any server.

## Key design decisions & tradeoffs

- **Embedding corpus in system prompt over RAG (for now).** With a ~3k-token corpus, stuffing the whole thing into the system prompt is simpler and cheaper than standing up embeddings and a vector store. RAG is the natural next step and a good learning exercise, but it wouldn't measurably improve answers at this corpus size.
- **Free models over paid.** Zero running cost was a hard goal, and the free models handle resume questions well. The cost of that choice is the 50 requests/day account cap, which the per-IP rate limit exists to protect.
- **Per-IP rate limiting over an off-topic gate.** A pre-filter that classifies every question before answering would add latency to every legitimate request, to defend against abuse that is hypothetical, free, and self-healing (the quota resets daily). I chose to bound the damage with a per-IP daily limit instead, and left the gate as an option to revisit if real abuse shows up.
- **Client-held conversation history over server storage.** Keeping history in the browser keeps the Worker stateless, sidesteps the problem of identifying anonymous users, and means I never store anyone's conversation.

## Security & abuse model

Everything arriving at the Worker is treated as untrusted, and a few layers handle that:

- **CORS** restricts which origins a browser will let call the Worker, so another website's front-end can't drive the bot through its visitors' browsers.
- **Per-IP rate limiting** (in Workers KV) caps any single IP's daily questions, protecting the shared request budget.
- **System Prompt** — the system prompt tells the model to answer only from the corpus and to ignore instructions embedded in user input, and the Worker only accepts \`user\`/\`assistant\` roles in replayed history, so a client can't smuggle in a fake \`system\` message.
- **Escape-first rendering** — model output is rendered as untrusted content (HTML is escaped, links are scheme-checked), because a prompt-injected model is effectively untrusted input inside my page.

The honest gap I live with for now is that the Worker URL is public. CORS only binds browsers, so a non-browser client (curl, a script) can call the endpoint directly and spend requests. Real auth isn't a fix here — the whole point is to serve anonymous recruiters, who can't be asked to log in. The realistic tool, if abuse ever materializes, is a humanness challenge like Cloudflare Turnstile. Given that the models are free and the daily cap self-heals, the rate limiter is a reasonable place to stop for now.

## Cost & scaling

The total cost of building this entire project with Claude Code (using the Fable 5 model) was about $2, per the statusline in my Claude Code session. The running cost is $0 — the models and the Cloudflare / GitHub Pages tiers are all free. The one bottleneck is the 50 requests/day OpenRouter cap, which a small amount of credit or a low-cost paid model would remove.

`;
