// GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Re-run `npm run build:corpus` after changing site content.
export const CORPUS = `# Profile

{
  "name": "Rajat Manish Bhagat",
  "brandName": "Rajat Bhagat",
  "heroGreeting": "Hi, I'm Rajat 👋",
  "tagline": "Software engineer specializing in data platforms, cloud infrastructure, and backend systems. Most recently an Associate Principal Software Engineer on the Data Platform team at The Options Clearing Corporation.",
  "openToCallout": "🔍 Open to new opportunities in the Data Platform space",
  "location": "Chicago, USA",
  "email": "rajat.bhagat@gmail.com",
  "linkedin": "https://www.linkedin.com/in/rmbhagat/",
  "github": "https://github.com/rajatbhagat",
  "resume": "/Rajat-Bhagat-Resume.pdf",
  "metaDescription": "Rajat Manish Bhagat — Software Engineer specializing in data platforms, cloud, and backend systems.",
  "skills": [
    {
      "group": "Languages",
      "items": "Java, Python, TypeScript, JavaScript, Terraform, Ansible, C"
    },
    {
      "group": "Web & Frameworks",
      "items": "Spring Boot, Node.js, React, Redux, Next.js, Django, JUnit"
    },
    {
      "group": "Databases",
      "items": "Snowflake, PostgreSQL, Oracle Database, MySQL, MongoDB"
    },
    {
      "group": "Cloud & Tools",
      "items": "AWS, Kafka, OpenShift, Oracle Cloud, Kubernetes, Docker, Jenkins, Git, Linux"
    }
  ],
  "highlights": [
    "7+ years of software engineering experience across fintech and cloud",
    "Master's in Computer Science, Northeastern University (GPA: 4.0)",
    "AWS Certified Solutions Architect – Associate (2025)",
    "Oracle Cloud Infrastructure Associate Architect & Cloud Developer Professional (2023)",
    "Impact Award recipient, 2 consecutive years at JP Morgan Chase"
  ],
  "education": {
    "school": "Northeastern University, Boston",
    "degree": "Master's in Computer Science",
    "period": "Aug 2021 – May 2023",
    "detail": "GPA: 4.0"
  },
  "certifications": [
    "AWS Certified Solutions Architect – Associate (2025)",
    "Oracle Cloud Infrastructure Associate Architect (2023)",
    "Oracle Cloud Infrastructure Cloud Developer Professional (2023)",
    "Impact Award for 2 consecutive years at JP Morgan Chase"
  ]
}


# Work Experience

---
company: Discover Financial Services
location: Chicago, US
title: Application Engineer
period: Apr 2024 – Oct 2025
order: 2
---

- Spearheaded development and enhancement of Config Manager, a Python-based microservice orchestrating artifact generation and deployment of over 200,000 artifacts
- Enhanced a custom reconciliation framework in Python enabling reusable validation controls, improving data quality assurance across 400 data pipelines
- Led testing and integration of multiple source systems, coordinating with 5 cross-functional teams for seamless deployment and post-launch enhancements
- Maintained the legacy Java-based Universal Data Loader processing 1M+ records daily, debugging issues and supporting AWS component integrations
- Implemented OpenShift (OCP) deployments with Helm charts and Docker via custom Jenkins CI/CD pipelines for 15 microservices


---

---
company: JP Morgan Chase
location: Mumbai, India
title: Software Engineer II
period: Jul 2018 – Jul 2021
order: 4
---

- Led development of a Trade Inquiry Chatbot on Symphony using Java Spring Boot, decreasing manual inquiries by 40%
- Spearheaded automation of loan claim transactions and built a new ReactJS portal, achieving a 60% automation rate
- Led a team of 3 developers building a Python document data extraction service extracting 40+ crucial data points
- Implemented a document digitization application with 5 Java microservices processing 700+ transactions daily
- Engineered an NLP service in Java Spring Boot with Apache OpenNLP and custom models, attaining 99% accuracy extracting keywords and codes from documents
- Established Kafka as the communication medium between microservices; delivered 20 production releases


---

---
company: Mythics LLC
location: Arlington, US
title: Cloud Developer
period: Jun 2023 – Mar 2024
order: 3
---

- Developed a real-time cloud cost monitoring portal using Next.js, Node.js, and Redux, reducing cloud expenses by 20%
- Improved portal performance with Redis caching (1 min → 2 sec) and enabled scalability by deploying on Kubernetes as Docker images
- Automated patching of Oracle Exadata machines with Ansible playbooks, saving 8+ hours of manual effort quarterly
- Deployed a Jenkins pipeline triggered by JIRA ticket transitions, reducing patching time by 60% and enabling parallel patching
- Orchestrated OCI resource provisioning for 4 customers using Terraform


---

---
company: The Options Clearing Corporation
location: Chicago, US
title: Associate Principal Software Engineer — Data Platform
period: Nov 2025 – Jun 2026
order: 1
# TODO(Rajat): The bullets below are drafts — replace them with your actual work at OCC.
---

- Worked on the Data Platform team building and maintaining data infrastructure for clearing and risk operations
- Designed and developed data pipelines and platform services supporting business-critical workloads
- Collaborated with cross-functional teams to deliver reliable, well-governed data products



# Projects

---
name: Food Recommender
tech: [Node.js, JavaScript, MongoDB]
links:
  - label: GitHub
    url: https://github.com/rajatbhagat/food-recommender-server
order: 3
---

Backend server for a food recommendation application that suggests dishes and restaurants based on user preferences.


---

---
name: Hotel Reservation System
tech: [Java, Spring Boot, React, MySQL]
links:
  - label: Backend
    url: https://github.com/rajatbhagat/hotel-reservation-spring-boot
  - label: Frontend
    url: https://github.com/rajatbhagat/hotel-reservation-react-app
order: 2
---

A full-stack hotel booking application with a Spring Boot REST backend and a React frontend covering room search, reservations, and booking management.


---

---
name: Mini-S3
tech: [Java, Spring Boot, PostgreSQL, React, Next.js, TypeScript]
links:
  - label: Backend
    url: https://github.com/rajatbhagat/mini-s3
  - label: UI
    url: https://github.com/rajatbhagat/mini-s3-ui
order: 1
---

An S3-compatible object storage service built from scratch to understand object storage internals — bucket management, object versioning, custom metadata, and a RESTful API, plus a React/Next.js UI with drag-and-drop uploads.


---

---
name: Music Recommendation System
tech: [Python, Jupyter, scikit-learn]
links:
  - label: GitHub
    url: https://github.com/rajatbhagat/music-recommendation-system
order: 4
---

A machine-learning based music recommendation system exploring collaborative filtering and content-based approaches.



# Blog Posts

---
title: 'Building Mini-S3: Learning Object Storage by Reimplementing It'
description: 'Why I built an S3-compatible object storage service from scratch with Spring Boot and PostgreSQL, and what it taught me.'
pubDate: 2026-07-09
category: tech
tags: [java, spring-boot, aws, s3, postgresql]
---

I've used AWS S3 for years — uploading artifacts, hosting static assets, wiring it into data pipelines. But using a service and understanding it are different things. So I decided to build my own: [Mini-S3](https://github.com/rajatbhagat/mini-s3), an S3-compatible object storage service in Spring Boot and PostgreSQL, with a [React/Next.js UI](https://github.com/rajatbhagat/mini-s3-ui) on top.

## What it does

Mini-S3 implements the core ideas of object storage:

- **Buckets** — top-level containers with validation rules (naming, empty-bucket deletion checks)
- **Objects** — upload, download, and delete files with their metadata
- **Versioning** — every change to an object keeps its full history
- **Custom metadata** — arbitrary key-value pairs attached to objects at upload time
- **A RESTful API** — clean endpoints that mirror how S3's own API is shaped

The UI adds drag-and-drop uploads, bucket browsing, and metadata views in friendly tables.

## What building it taught me

**Versioning is a data-modeling problem, not a storage problem.** The interesting part isn't storing multiple copies — it's deciding what "the current version" means, how deletes interact with history, and how to keep queries fast when every object is really a chain of versions.

**Metadata design matters more than it looks.** S3's split between system metadata and user metadata seemed arbitrary until I had to implement both and realized they have completely different consistency and validation needs.

**API ergonomics come from constraints.** Reproducing S3-style semantics (like refusing to delete a non-empty bucket) forced me to think about *why* AWS made those choices — usually the answer is protecting users from themselves.

## Managing it like a real project

I ran the build like a work project, with a JIRA board, epics, and 175+ tasks. That sounds like overkill for a personal repo, but it kept the scope honest and made it easy to pick the project back up after breaks.

If you've ever wanted to demystify a cloud service you use daily, I highly recommend reimplementing a toy version. You'll never look at the real thing the same way.


---

---
title: 'Hello World: How This Blog Works'
description: 'The first post — and a living guide to how I add new posts and categories to this site.'
pubDate: 2026-07-09
category: tech
tags: [astro, meta, blogging]
---

Welcome! This is my corner of the internet — part portfolio, part blog. I'll write here about technology I'm working with, movies I've watched, and whatever else earns a category.

This first post doubles as documentation for future me: here's how the blog actually works.

## The stack

The site is built with [Astro](https://astro.build), a static site generator that treats markdown as a first-class citizen. Every page is pre-rendered to plain HTML, so it's fast and hosts for free on GitHub Pages. A GitHub Actions workflow rebuilds and deploys the site on every push to \`main\`.

## Adding a post

Each post is a single markdown file in \`src/content/blog/\`. To publish a new one, I add a file like this:

\`\`\`markdown
---
title: 'My New Post'
description: 'One-line summary shown in listings and search results.'
pubDate: 2026-08-01
category: tech
tags: [optional, tags]
---

The post content, in plain markdown.
\`\`\`

Commit, push, and it's live a minute later. That's the whole workflow.

## Categories are free

There's no registry of categories. The \`category\` frontmatter field can be anything — \`tech\`, \`movies\`, \`books\`, \`travel\` — and the site automatically generates a listing page at \`/blog/category/<name>/\` for every category that has at least one post. Adding a new category is just using it.

## Drafts

Setting \`draft: true\` in the frontmatter keeps a post out of the build entirely. I keep half-written posts in the repo without publishing them.

That's it — see you in the next post.
`;
